# Markdown
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /:title.html
exclude: ["Makefile", "README.md", "_/Gemfile", "_/Gemfile.lock",  "CNAME"]

# Site info
url: "http://siteurl.com"
meta:
  title: "Site name"
  description: "This is the site description"

# Google analytics
analytics:
  hostname: "siteurl.com"
  id: "UA-XXXXXXXX-1"

# Collections
collections:
  - authors

# Default variables
defaults:
  - scope:
      path: ""
    values:
      layout: "article"
      tags: []
      author: John Smith
